---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8081}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: nginx
    run_list:
        - recipe[nginx]
    attributes:

  - name: fiverr_nginx
    run_list:
        - recipe[nginx-example]
    attributes:
